### ISSUE TITLE
Support reading pin meta v0

### ISSUE THREAD

**Issue by machow** [machow/pins-python#63]
Because metadata is used in pin_search, pin_read, and (trivially) pin_meta, we need to support pins v0's metadata format. This is probably most important for pin_search, since it w/o it you can't discover pins on the board.

See R code here:

https://github.com/rstudio/pins/blob/main/R/pin-meta.R#L58-L65

Let's follow it, and set these fields to something None-ish if they're not in `data.txt`: type, title, created, file_size.

Edit: here's an internal example I found (`nathan/mtcars2/30957/data.txt`)

```
path:
- data.csv
- data.rds
rows: 32
cols: 11
columns:
  mpg: numeric
  cyl: numeric
  disp: numeric
  hp: numeric
  drat: numeric
  wt: numeric
  qsec: numeric
  vs: numeric
  am: numeric
  gear: numeric
  carb: numeric
description: The motor trend cars data set
type: table
```

Looks like missing fields are:

* title
* created
* pin_hash
* file (named path)
* file_size
* api_version
* user
